import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
import numpy as np


SCRIPT_DIR = Path(__file__).resolve().parent


def parse_args():
    parser = argparse.ArgumentParser(
        description="Plot token-count based memory consumption over time."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=SCRIPT_DIR / "eval_mixed_prompt_retrain.csv",
        help="CSV generated by evaluate_rl_policy_on_mvvit.py, evaluate_train_policy_on_mvvit.py, or main_edge_cloud_new.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=SCRIPT_DIR / "token_count_over_time.png",
    )
    parser.add_argument(
        "--curve-output",
        type=Path,
        default=None,
        help="Optional CSV path for the plotted curve values.",
    )
    parser.add_argument("--time-col", type=str, default="sample_id")
    parser.add_argument(
        "--token-ratio-col",
        type=str,
        default="auto",
        help=(
            "Column containing the sum of token keep ratios across views. "
            "Use auto to prefer active_token_ratio_sum in RL logs and "
            "effective_token_ratio_sum in evaluation logs."
        ),
    )
    parser.add_argument("--num-views", type=int, default=4)
    parser.add_argument("--tokens-per-view", type=int, default=196)
    parser.add_argument(
        "--window",
        type=int,
        default=100,
        help="Moving-average window for token count.",
    )
    parser.add_argument(
        "--mode",
        type=str,
        default="raw",
        choices=["raw", "moving", "block"],
    )
    parser.add_argument(
        "--style",
        type=str,
        default="step",
        choices=["line", "step", "scatter", "line_scatter"],
        help="raw + step is best for showing real-time decision changes.",
    )
    parser.add_argument(
        "--color-by-u",
        action="store_true",
        help="Overlay policy points colored by u decisions when the CSV has a u column.",
    )
    parser.add_argument(
        "--focus-policy",
        action="store_true",
        help="Use a two-band plot: full-token baseline at the top and zoomed Ours curve below.",
    )
    parser.add_argument(
        "--policy-y-pad",
        type=float,
        default=20.0,
        help="Padding around the Ours y-range when --focus-policy is enabled.",
    )
    parser.add_argument(
        "--policy-y-step",
        type=float,
        default=None,
        help="Optional y tick interval for the zoomed Ours axis.",
    )
    parser.add_argument("--title", type=str, default="Token Count Over Time")
    parser.add_argument("--baseline-label", type=str, default="full views+full tokens")
    parser.add_argument("--policy-label", type=str, default="Ours")
    parser.add_argument(
        "--include-cls",
        action="store_true",
        help="Add 1 CLS token to both curves.",
    )
    parser.add_argument(
        "--include-prompt",
        action="store_true",
        help="Add prompt tokens for rows whose used_prompt column equals 1.",
    )
    parser.add_argument("--num-prompt-tokens", type=int, default=4)
    return parser.parse_args()


def load_rows(path):
    if not path.exists():
        raise FileNotFoundError(f"Input CSV not found: {path}")

    with path.open("r", newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    if not rows:
        raise ValueError(f"Input CSV is empty: {path}")
    return rows


def get_float_column(rows, column, default=None):
    values = []
    for idx, row in enumerate(rows):
        if column not in row or row[column] == "":
            if default is None:
                raise ValueError(f"Missing required column: {column}")
            values.append(default(idx, row))
        else:
            values.append(float(row[column]))
    return np.asarray(values, dtype=np.float64)


def has_column(rows, column):
    return bool(rows) and column in rows[0]


def auto_token_ratio_sum(rows, args):
    if args.token_ratio_col != "auto":
        return get_float_column(rows, args.token_ratio_col), args.token_ratio_col

    if has_column(rows, "active_token_ratio_sum"):
        return get_float_column(rows, "active_token_ratio_sum"), "active_token_ratio_sum"

    if has_column(rows, "effective_token_ratio_sum"):
        return get_float_column(rows, "effective_token_ratio_sum"), "effective_token_ratio_sum"

    effective_cols = [f"k_effective_{i + 1}" for i in range(args.num_views)]
    if all(has_column(rows, col) for col in effective_cols):
        values = sum(get_float_column(rows, col) for col in effective_cols)
        return values, "sum(k_effective_i)"

    policy_k_cols = [f"k_{i + 1}" for i in range(args.num_views)]
    policy_v_cols = [f"v_{i + 1}" for i in range(args.num_views)]
    if all(has_column(rows, col) for col in policy_k_cols):
        values = np.zeros(len(rows), dtype=np.float64)
        for idx in range(args.num_views):
            k_values = get_float_column(rows, policy_k_cols[idx])
            if has_column(rows, policy_v_cols[idx]):
                v_values = get_float_column(rows, policy_v_cols[idx])
                k_values = k_values * v_values
            values += k_values
        return values, "sum(v_i * k_i)"

    raise ValueError(
        "Could not infer token ratio sum. Pass --token-ratio-col explicitly."
    )


def moving_average(values, window):
    window = max(1, int(window))
    kernel = np.ones(window, dtype=np.float64)
    sums = np.convolve(values, kernel, mode="same")
    counts = np.convolve(np.ones_like(values, dtype=np.float64), kernel, mode="same")
    return sums / np.maximum(counts, 1.0)


def block_average(x, values, window):
    window = max(1, int(window))
    block_x = []
    block_values = []
    for start in range(0, len(values), window):
        end = min(start + window, len(values))
        block_x.append(np.mean(x[start:end]))
        block_values.append(np.mean(values[start:end]))
    return np.asarray(block_x), np.asarray(block_values)


def compute_curve(x, baseline_tokens, policy_tokens, args):
    if args.mode == "raw":
        return x, baseline_tokens, x, policy_tokens

    if args.mode == "block":
        baseline_x, baseline_y = block_average(x, baseline_tokens, args.window)
        policy_x, policy_y = block_average(x, policy_tokens, args.window)
        return baseline_x, baseline_y, policy_x, policy_y

    return x, moving_average(baseline_tokens, args.window), x, moving_average(policy_tokens, args.window)


def save_curve_csv(path, baseline_x, baseline_y, policy_x, policy_y):
    path.parent.mkdir(parents=True, exist_ok=True)
    length = max(len(baseline_x), len(policy_x))
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "baseline_time",
                "baseline_tokens",
                "policy_time",
                "policy_tokens",
            ],
        )
        writer.writeheader()
        for idx in range(length):
            writer.writerow(
                {
                    "baseline_time": "" if idx >= len(baseline_x) else float(baseline_x[idx]),
                    "baseline_tokens": "" if idx >= len(baseline_y) else float(baseline_y[idx]),
                    "policy_time": "" if idx >= len(policy_x) else float(policy_x[idx]),
                    "policy_tokens": "" if idx >= len(policy_y) else float(policy_y[idx]),
                }
            )


def plot_series(ax, x, y, label, color, linewidth, style):
    if style == "scatter":
        ax.scatter(x, y, label=label, color=color, s=12, alpha=0.75)
        return

    drawstyle = "steps-post" if style == "step" else "default"
    ax.plot(
        x,
        y,
        label=label,
        color=color,
        linewidth=linewidth,
        drawstyle=drawstyle,
    )

    if style == "line_scatter":
        ax.scatter(x, y, color=color, s=8, alpha=0.55)


def overlay_u_points(ax, rows, x, policy_tokens):
    if not has_column(rows, "u"):
        print("Warning: --color-by-u ignored because input CSV has no u column.")
        return

    u_values = get_float_column(rows, "u").astype(int)
    colors = {
        0: "#1f77b4",
        1: "#ff7f0e",
        2: "#2ca02c",
    }
    labels = {
        0: "Ours u=0",
        1: "Ours u=1",
        2: "Ours u=2",
    }
    for u_value in [0, 1, 2]:
        mask = u_values == u_value
        if np.any(mask):
            ax.scatter(
                x[mask],
                policy_tokens[mask],
                s=14,
                color=colors[u_value],
                alpha=0.75,
                label=labels[u_value],
                zorder=3,
            )


def apply_policy_axis_limits(ax, values, args):
    y_min = float(np.min(values))
    y_max = float(np.max(values))
    dynamic_pad = max((y_max - y_min) * 0.08, args.policy_y_pad)
    ax.set_ylim(max(0.0, y_min - dynamic_pad), y_max + dynamic_pad)
    if args.policy_y_step is not None and args.policy_y_step > 0:
        ax.yaxis.set_major_locator(MultipleLocator(args.policy_y_step))


def plot_standard_figure(
    args,
    rows,
    baseline_x,
    baseline_y,
    policy_x,
    policy_y,
    x,
    policy_tokens,
):
    plt.figure(figsize=(10, 5.2), dpi=160)
    ax = plt.gca()

    plot_series(
        ax,
        baseline_x,
        baseline_y,
        args.baseline_label,
        "#7f7f7f",
        2.0,
        "line",
    )
    plot_series(
        ax,
        policy_x,
        policy_y,
        args.policy_label,
        "#1f77b4",
        2.2,
        args.style,
    )

    if args.color_by_u and args.mode == "raw":
        overlay_u_points(ax, rows, x, policy_tokens)
    elif args.color_by_u:
        print("Warning: --color-by-u is only applied when --mode raw.")

    ax.set_title(args.title)
    ax.set_xlabel("Time")
    ax.set_ylabel("Number of Tokens")
    ax.grid(True, linestyle="--", linewidth=0.6, alpha=0.35)
    ax.legend(loc="best", frameon=True)
    plt.tight_layout()
    plt.savefig(args.output, bbox_inches="tight")
    plt.close()


def plot_focus_policy_figure(
    args,
    rows,
    baseline_x,
    baseline_y,
    policy_x,
    policy_y,
    x,
    policy_tokens,
):
    fig, (ax_top, ax_bottom) = plt.subplots(
        2,
        1,
        sharex=True,
        figsize=(10, 5.8),
        dpi=160,
        gridspec_kw={"height_ratios": [1, 4], "hspace": 0.08},
    )

    full_token_value = float(np.mean(baseline_y))
    top_pad = max(5.0, full_token_value * 0.015)
    plot_series(
        ax_top,
        baseline_x,
        baseline_y,
        args.baseline_label,
        "#7f7f7f",
        2.0,
        "line",
    )
    ax_top.set_ylim(full_token_value - top_pad, full_token_value + top_pad)
    ax_top.set_ylabel("Full")
    ax_top.grid(True, linestyle="--", linewidth=0.6, alpha=0.30)
    ax_top.tick_params(labelbottom=False)
    ax_top.legend(loc="upper right", frameon=True)
    ax_top.text(
        0.01,
        0.70,
        f"{args.baseline_label}: {full_token_value:.0f}",
        transform=ax_top.transAxes,
        ha="left",
        va="center",
        fontsize=9,
        color="#555555",
    )

    plot_series(
        ax_bottom,
        policy_x,
        policy_y,
        args.policy_label,
        "#1f77b4",
        2.2,
        args.style,
    )

    if args.color_by_u and args.mode == "raw":
        overlay_u_points(ax_bottom, rows, x, policy_tokens)
    elif args.color_by_u:
        print("Warning: --color-by-u is only applied when --mode raw.")

    apply_policy_axis_limits(ax_bottom, policy_y, args)
    ax_bottom.set_xlabel("Time")
    ax_bottom.set_ylabel("Number of Tokens")
    ax_bottom.grid(True, linestyle="--", linewidth=0.6, alpha=0.35)
    ax_bottom.legend(loc="best", frameon=True)
    fig.suptitle(args.title, y=0.98)
    plt.tight_layout()
    plt.savefig(args.output, bbox_inches="tight")
    plt.close()


def main():
    args = parse_args()
    rows = load_rows(args.input)

    x = get_float_column(rows, args.time_col, default=lambda idx, _row: idx)
    ratio_sum, ratio_source = auto_token_ratio_sum(rows, args)

    full_tokens = args.num_views * args.tokens_per_view
    baseline_tokens = np.full(len(rows), full_tokens, dtype=np.float64)
    policy_tokens = ratio_sum * args.tokens_per_view

    if args.include_cls:
        baseline_tokens = baseline_tokens + 1
        policy_tokens = policy_tokens + 1

    if args.include_prompt:
        used_prompt = get_float_column(rows, "used_prompt", default=lambda _idx, _row: 0.0)
        policy_tokens = policy_tokens + used_prompt * args.num_prompt_tokens

    baseline_x, baseline_y, policy_x, policy_y = compute_curve(
        x,
        baseline_tokens,
        policy_tokens,
        args,
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    curve_output = args.curve_output
    if curve_output is None:
        curve_output = args.output.with_suffix(".csv")
    save_curve_csv(curve_output, baseline_x, baseline_y, policy_x, policy_y)

    plt.rcParams["axes.unicode_minus"] = False
    if args.focus_policy:
        plot_focus_policy_figure(
            args,
            rows,
            baseline_x,
            baseline_y,
            policy_x,
            policy_y,
            x,
            policy_tokens,
        )
    else:
        plot_standard_figure(
            args,
            rows,
            baseline_x,
            baseline_y,
            policy_x,
            policy_y,
            x,
            policy_tokens,
        )

    saving = 1.0 - policy_tokens.mean() / max(baseline_tokens.mean(), 1.0)
    print(f"Saved figure: {args.output}")
    print(f"Saved curve CSV: {curve_output}")
    print(f"Token ratio source: {ratio_source}")
    print(f"Average baseline tokens: {baseline_tokens.mean():.4f}")
    print(f"Average policy tokens: {policy_tokens.mean():.4f}")
    print(f"Average token saving: {saving:.4%}")


if __name__ == "__main__":
    main()
