import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


SCRIPT_DIR = Path(__file__).resolve().parent


def parse_args():
    parser = argparse.ArgumentParser(
        description="Plot baseline and RL-policy accuracy curves over time."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=SCRIPT_DIR / "eval_mixed_prompt_retrain.csv",
        help="CSV generated by evaluate_rl_policy_on_mvvit.py or evaluate_train_policy_on_mvvit.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=SCRIPT_DIR / "accuracy_over_time.png",
        help="Output figure path.",
    )
    parser.add_argument(
        "--curve-output",
        type=Path,
        default=None,
        help="Optional CSV path for the plotted curve values.",
    )
    parser.add_argument(
        "--window",
        type=int,
        default=100,
        help="Sliding window size. A larger value makes the accuracy curve smoother.",
    )
    parser.add_argument(
        "--mode",
        type=str,
        default="moving",
        choices=["moving", "cumulative", "block"],
        help="moving: sliding-window accuracy; cumulative: accuracy from time 0 to t; block: non-overlap window accuracy.",
    )
    parser.add_argument(
        "--time-col",
        type=str,
        default="sample_id",
        help="Column used as timestamp. Falls back to row index if missing.",
    )
    parser.add_argument(
        "--baseline-col",
        type=str,
        default="baseline_correct",
        help="Correctness column for the no-action baseline.",
    )
    parser.add_argument(
        "--policy-col",
        type=str,
        default="rl_policy_correct",
        help="Correctness column for the proposed algorithm.",
    )
    parser.add_argument(
        "--baseline-label",
        type=str,
        default="full views+full tokens",
    )
    parser.add_argument(
        "--policy-label",
        type=str,
        default="Ours",
    )
    parser.add_argument("--title", type=str, default="Accuracy Over Time")
    parser.add_argument("--ylim-min", type=float, default=0.0)
    parser.add_argument("--ylim-max", type=float, default=100.0)
    parser.add_argument(
        "--show-drift",
        action="store_true",
        help="Shade background regions according to drift_type if the column exists.",
    )
    return parser.parse_args()


def load_eval_rows(path):
    if not path.exists():
        raise FileNotFoundError(f"Input CSV not found: {path}")

    with path.open("r", newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    if not rows:
        raise ValueError(f"Input CSV is empty: {path}")
    return rows


def get_float_column(rows, column, default=None):
    values = []
    for idx, row in enumerate(rows):
        if column not in row or row[column] == "":
            if default is None:
                raise ValueError(f"Missing required column: {column}")
            values.append(default(idx))
        else:
            values.append(float(row[column]))
    return np.asarray(values, dtype=np.float64)


def moving_accuracy(correct, window):
    window = max(1, int(window))
    kernel = np.ones(window, dtype=np.float64)
    sums = np.convolve(correct, kernel, mode="same")

    counts = np.convolve(np.ones_like(correct, dtype=np.float64), kernel, mode="same")
    return sums / np.maximum(counts, 1.0)


def cumulative_accuracy(correct):
    counts = np.arange(1, len(correct) + 1, dtype=np.float64)
    return np.cumsum(correct) / counts


def block_accuracy(x, correct, window):
    window = max(1, int(window))
    block_x = []
    block_acc = []
    for start in range(0, len(correct), window):
        end = min(start + window, len(correct))
        block_x.append(np.mean(x[start:end]))
        block_acc.append(np.mean(correct[start:end]))
    return np.asarray(block_x), np.asarray(block_acc)


def compute_curves(x, baseline_correct, policy_correct, args):
    if args.mode == "cumulative":
        return x, cumulative_accuracy(baseline_correct), x, cumulative_accuracy(policy_correct)

    if args.mode == "block":
        baseline_x, baseline_acc = block_accuracy(x, baseline_correct, args.window)
        policy_x, policy_acc = block_accuracy(x, policy_correct, args.window)
        return baseline_x, baseline_acc, policy_x, policy_acc

    return (
        x,
        moving_accuracy(baseline_correct, args.window),
        x,
        moving_accuracy(policy_correct, args.window),
    )


def add_drift_background(ax, rows, x):
    if "drift_type" not in rows[0]:
        return

    colors = {
        "normal": "#ffffff",
        "bright": "#fff4c2",
        "dark": "#d9e2f3",
        "blur": "#e2f0d9",
        "noise": "#fce4d6",
        "occlusion": "#eadcf8",
        "multi_view_failure": "#f4cccc",
    }

    start = 0
    current = rows[0].get("drift_type", "normal")
    for idx in range(1, len(rows) + 1):
        drift_type = rows[idx].get("drift_type", "normal") if idx < len(rows) else None
        if drift_type != current:
            x0 = x[start]
            x1 = x[idx - 1]
            ax.axvspan(
                x0,
                x1,
                color=colors.get(current, "#eeeeee"),
                alpha=0.18,
                linewidth=0,
            )
            if current and current != "normal":
                ax.text(
                    (x0 + x1) / 2,
                    2.0,
                    current,
                    ha="center",
                    va="bottom",
                    fontsize=8,
                    color="#666666",
                )
            start = idx
            current = drift_type


def save_curve_csv(path, baseline_x, baseline_acc, policy_x, policy_acc):
    path.parent.mkdir(parents=True, exist_ok=True)
    length = max(len(baseline_x), len(policy_x))
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "baseline_time",
                "baseline_accuracy",
                "policy_time",
                "policy_accuracy",
            ],
        )
        writer.writeheader()
        for idx in range(length):
            writer.writerow(
                {
                    "baseline_time": "" if idx >= len(baseline_x) else float(baseline_x[idx]),
                    "baseline_accuracy": "" if idx >= len(baseline_acc) else float(baseline_acc[idx]),
                    "policy_time": "" if idx >= len(policy_x) else float(policy_x[idx]),
                    "policy_accuracy": "" if idx >= len(policy_acc) else float(policy_acc[idx]),
                }
            )


def main():
    args = parse_args()
    rows = load_eval_rows(args.input)

    x = get_float_column(rows, args.time_col, default=lambda idx: idx)
    baseline_correct = get_float_column(rows, args.baseline_col)
    policy_correct = get_float_column(rows, args.policy_col)

    baseline_x, baseline_acc, policy_x, policy_acc = compute_curves(
        x,
        baseline_correct,
        policy_correct,
        args,
    )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    curve_output = args.curve_output
    if curve_output is None:
        curve_output = args.output.with_suffix(".csv")
    save_curve_csv(curve_output, baseline_x, baseline_acc, policy_x, policy_acc)

    plt.rcParams["axes.unicode_minus"] = False
    plt.figure(figsize=(10, 5.2), dpi=160)
    ax = plt.gca()

    if args.show_drift:
        add_drift_background(ax, rows, x)

    ax.plot(
        baseline_x,
        baseline_acc * 100.0,
        label=args.baseline_label,
        color="#7f7f7f",
        linewidth=2.0,
    )
    ax.plot(
        policy_x,
        policy_acc * 100.0,
        label=args.policy_label,
        color="#1f77b4",
        linewidth=2.2,
    )

    ax.set_title(args.title)
    ax.set_xlabel("Time")
    ax.set_ylabel("Accuracy (%)")
    ax.set_ylim(args.ylim_min, args.ylim_max)
    ax.grid(True, linestyle="--", linewidth=0.6, alpha=0.35)
    ax.legend(loc="best", frameon=True)
    plt.tight_layout()
    plt.savefig(args.output, bbox_inches="tight")
    plt.close()

    print(f"Saved figure: {args.output}")
    print(f"Saved curve CSV: {curve_output}")
    print(f"Baseline final mean accuracy: {baseline_correct.mean() * 100.0:.4f}%")
    print(f"Policy final mean accuracy: {policy_correct.mean() * 100.0:.4f}%")


if __name__ == "__main__":
    main()
